### PR TITLE
refactor(core): Rename "job" table to "runs" and "job_id" to "job_name"

### LINKED ISSUE #2035: Rename of internal (OLTP) "Job" tables and columns
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/2079

Originally created by @DouweM on 2020-05-29 15:15:14

---

- [ ] Rename `job` table to `run(s)`
- [ ] Rename `job_id` column to `job_name`

Note: Since the concept of 'job' itself is changing, we should either wait until [#2924](https://gitlab.com/meltano/meltano/-/issues/2924) is shipped - or else combine this with that.

### PR DESCRIPTION
**Pull request by cjohnhanson**
Closes #2035

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]
lgtm 👌

**Review by pandemicsyn — APPROVED** [review]
🚀

**Comment by pdebelak** [comment]
This appears to be a breaking change if you use a version of sqlite3 less that 3.25.1 (see changelog https://sqlite.org/releaselog/3_25_1.html for the addition of `ALTER TABLE RENAME` in that version). Notably, this means that meltano 2.1.0 works on ubuntu 18.04 but not meltano 2.2.0. This generates a syntax error for earlier versions of sqlite:

```
(sqlite3.OperationalError) near "job_id": syntax error
[SQL: ALTER TABLE job RENAME job_id TO job_name]
INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by edgarrmondragon** [comment]
@pdebelak thanks for reporting! This sounds like something we should document 🙂

https://github.com/meltano/meltano/issues/6405

**Pull request merged**
