### PR TITLE
docs: Update link to Meltano dbt Jaffle shop example

### PR DESCRIPTION
**Pull request by flexponsive**
It appears there is a more up to date version of the jaffle shop example in the meltano organization now

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]

**Review by WillDaSilva — APPROVED** [review]
Thanks @flexponsive!

**Review by tayloramurphy — APPROVED** [review]
I think this is right! @aaronsteers @pnadolny13 will you double check me here.

**Comment by pnadolny13** [comment]
@tayloramurphy linking to an official demo vs my personal repo seems like a good idea. Although there is a slight difference. The new jaffle shop repo installs dbt standalone next to Meltano vs installing dbt as a utility.

**Comment by tayloramurphy** [comment]
@pnadolny13 the one in this PR is a full Meltano project. It's downstream of the main dbt labs one and has quite a few more commites.

**Review by edgarrmondragon — APPROVED** [review]

**Pull request merged**
