### PR TITLE
Fix telemetry state change event

### LINKED ISSUE #6123: Telemetry - State change not firing
Related to https://github.com/meltano/meltano/issues/6032

I havent seen any state change events come through yet and I tried my best to get them to fire locally with no luck. I confirmed I didnt have any anonymous usage settings in my environment, then ran these steps with my pip install version 2.0.0:

1. Init project `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano init test_opt_out_1`
1. `cd test_opt_out_1` Note I dont see an analytics.json file in my .meltano folder
```yaml
version: 1
default_environment: dev
project_id: 327b8c41-e2ce-4dce-a70c-fac6adeb42d9
environments:
- name: dev
- name: staging
- name: prod
```
3. Add tap-csv `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano add extractor tap-csv`
- I see a structured event fire (unstruct events were added but havent been released yet)
4. Copy/Paste config to tap-csv so it will run without failing
```yaml
version: 1
default_environment: dev
project_id: 327b8c41-e2ce-4dce-a70c-fac6adeb42d9
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: [MY_PATH]/customers.csv
            keys:
            - id
- name: staging
- name: prod
```
6. Invoke tap-csv `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano invoke tap-csv`
- I see unstruct start and complete events plus the legacy struct event
7. Add `send_anonymous_usage_stats: false` to my meltano.yml and run again `MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS='["http://localhost:9090"]' meltano invoke tap-csv` 
- No events fired at all

cc @tayloramurphy @aaronsteers @WillDaSilva @pandemicsyn

### PR DESCRIPTION
**Pull request by WillDaSilva**
Closes #6123

### CODE REVIEW

**Review by pandemicsyn — CHANGES_REQUESTED** [review]
If you've got time, can you add a quicky test. Doesn't have to fully test Tracker() just testing state handling maybe? 

Alternatively, if you're still feeling time crunched could you instead maybe share before/after snow plow micro events and the local file having been created?

**Comment by WillDaSilva** [comment]
@pandemicsyn Do we have anything setup to run Docker containers under Pytest? I'm pretty uncomfortable with how we currently (don't) test telemetry, and it'd be great if we could spin-up Snowplow micro to ensure we're getting all the events/contexts we expect. If we don't have anything like this already, we can probably use https://github.com/avast/pytest-docker to help

**Comment by pandemicsyn** [comment]
@WillDaSilva we don't at the moment , but IMHO we should break this up into functional tests and plain unit tests. Starting with some unit tests would go along way. In that initial PR there was some brokeness with the Environment context generation, so when I added the PluginsContext I added some quick test coverage (https://github.com/meltano/meltano/blob/main/tests/meltano/core/tracking/test_plugins.py). 

If we can get some unittest coverage we can follow it up and augment it with some functional tests that run as part of CI that make sure things are landing in snowplow micro as expected.

**Review by pandemicsyn — APPROVED** [review]
lgtm!

**Review by pnadolny13 — APPROVED** [review]
@WillDaSilva I tested it working locally, functionally everything looks good to me!

**Pull request merged**
