### PR TITLE
docs: Document Git requirement and add `uv` section

### PR DESCRIPTION
**Pull request by edgarrmondragon**
## Description

- Updated page: https://deploy-preview-8950--meltano.netlify.app/guide/installation-guide

## Related Issues

* Slack: https://meltano.slack.com/archives/C06A1LKFAAC/p1733422132902619

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]

**Review by tayloramurphy — APPROVED** [review]
@edgarrmondragon I haven't done a thorough review of the content but at a glance it looks good. 

Question though - did the styling recently update? It seems like the code formatting now has italics for things like _--python_

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I haven't done a thorough review of the content but at a glance it looks good.
> 
> Question though - did the styling recently update? It seems like the code formatting now has italics for things like _--python_

@tayloramurphy it's possible a Docusaurus update broke styling in some places. In which page(s) did you notice that?

**Comment by tayloramurphy** [comment]
@edgarrmondragon anywhere there's code https://deploy-preview-8950--meltano.netlify.app/getting-started/installation/
Screenshot 2024-12-08 at 4 44 47 PM

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon anywhere there's code https://deploy-preview-8950--meltano.netlify.app/getting-started/installation/
> Screenshot 2024-12-08 at 4 44 47 PM
> 

@tayloramurphy Oh interesting, for some reason it's only styled like that in dark mode





I'll look into that

**Pull request merged**
