### PR TITLE
ci: Re-add CodeQL analysis GitHub workflow

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Restored code quality changes made by #6402 and later reverted by #6418, adding `crossorigin="anonymous"` for upstream JS resources.

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]

**Review by aaronsteers — CHANGES_REQUESTED** [review]
@edgarrmondragon - I think I'm missing some context on this PR and the description field is blank.

Can you explain a bit more (in docs or in the PR description) on the functions added here and what this delivers?

Thanks!

**Comment by WillDaSilva** [comment]
> I think I'm missing some context on this PR and the description field is blank.
> 
> Can you explain a bit more (in docs or in the PR description) on the functions added here and what this delivers?

@aaronsteers It starts with https://github.com/meltano/meltano/pull/6402, wherein I added a CodeQL analysis workflow. This workflow comes recommended by GitHub. It scans our code for vulnerabilities, then uploads the results to https://github.com/meltano/meltano/security/code-scanning for the branch it scanned.

In the original PR it discovered some issues, so I attempted to resolve them. One of these fixes was that we didn't have subresource integrity checks. To fix this I found the appropriate hashes for the resources we were loading, and added the checks. Unfortunately I neglected to add the `crossorigin="anonymous"` attribute. This broke the search feature in the docs, and later somehow took down the whole site. It went unnoticed during review, and once the changes were merged in @tayloramurphy noticed, and began a Slack thread: https://meltano.slack.com/archives/C02JXFEC9T2/p1657739197021349

To resolve the outage, we merged in https://github.com/meltano/meltano/pull/6418, which reverted the changes.

This PR re-adds the changes, along with `crossorigin="anonymous"` set as needed to avoid a similar breakage.

To avoid similar problems in the future, we'll need to improve our UI testing. There is an old issue about this (https://github.com/meltano/meltano/issues/501), but I don't think it's applicable anymore. A related (open) issue is
- https://github.com/meltano/meltano/issues/3212.

**Comment by edgarrmondragon** [comment]
@WillDaSilva thanks for jumping in!

That's exactly right.

**Review by aaronsteers — APPROVED** [review]
@WillDaSilva - Thanks for the detailed explanation. Very much appreciated. 🙏

**Comment by edgarrmondragon** [comment]
Merging, since search functionality works as expected...

**Pull request merged**
