### PR TITLE
Add badges to `README.md`

### LINKED ISSUE #6258: Add badges to `README.md`
Follow-up issue from https://github.com/meltano/internal-general/discussions/410

### PR DESCRIPTION
**Pull request by WillDaSilva**
Closes https://github.com/meltano/meltano/issues/6258

### CODE REVIEW

**Comment by WillDaSilva** [comment]
The rendered readme can be previewed here: https://github.com/meltano/meltano/blob/4ee1b1927d45bd30d0557182332a5a6cf851bbf4/README.md

**Comment by WillDaSilva** [comment]
I'm not sure why the GitHub tests badge is showing "no status" in the preview on GitHub. It's showing "passing" locally. Can anyone else try rendering the badge locally. Maybe it's just a problem with the preview, somehow.

**Review by afolson — APPROVED** [review]
@WillDaSilva Looks like the issue with the GitHub badge is resolved now? This looks great, thanks for adding it!

**Review by edgarrmondragon — APPROVED** [review]
@WillDaSilva looks great!

All badges are rendering fine btw

Screen Shot 2022-06-21 at 22 28 23

**Pull request merged**
