### PR TITLE
feat: Add meltano cloud "state" command

### PR DESCRIPTION
**Pull request by cjohnhanson**
Adds client functionality for [new Cloud state management API](https://github.com/meltano/infra/pull/2091)

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@cjohnhanson is this ready to do some UAT on? @pnadolny13 would you mind testing it once it's ready?

@cjohnhanson will you have a separate PR for the docs update too?

**Comment by cjohnhanson** [comment]
@tayloramurphy this is ready for UAT but the [corresponding infra PR](https://github.com/meltano/infra/pull/2091) has been deployed to sandbox only. Since part of UAT for this will require actually running stateful jobs, it might be easier to wait for that to deploy to staging before testing the new command. @pnadolny13 -- am I right in understanding that we generally don't configure secrets for or enable Squared jobs in sandbox?

> will you have a separate PR for the docs update too?
Yeah I've got that going in a separate branch off of this one, I thought it would be easier to review separately (and have a better-delineated set of changes for merging into main) but happy to just merge into this branch and have it all in one once it's ready later today.

**Review by edgarrmondragon — APPROVED** [review]

**Comment by pnadolny13** [comment]
@cjohnhanson sorry must have missed the notification on this ping.

>am I right in understanding that we generally don't configure secrets for or enable Squared jobs in sandbox?

Yeah I've never interacted with cloud infrastructure other than whats in production, so if theres anything there it wasnt me who set it up.

**Comment by cjohnhanson** [comment]
@pnadolny13 this is deployed in prod now, if you wanted to give it a quick UAT check.

**Comment by cjohnhanson** [comment]
@tayloramurphy -- heads up I've QA'ed all three of these commands for a sample schedule in Squared in prod. Mind giving it a final 👍 / 👎 ? 

If we're all good, I'll merge this and the docs changes and we can coordinate on announcing this to current Cloud users.

**Comment by pnadolny13** [comment]
@cjohnhanson is this working for you? I posted [in slack](https://internalmeltano.slack.com/archives/C05N4BJEQJE/p1693947572076119) about the cloud CLI command not being found for me and it seemed to affect this branch as well. I dont see the `cloud-cli` script in the pyproject.toml which made me suspect there was a bad merge, idk. Its also possible my local setup is messed up.

**Comment by cjohnhanson** [comment]
@pnadolny13 -- it was working for me prior to [merging in the latest changes from the target branch](https://github.com/meltano/meltano/commit/d4857c1cc5137d06504f01b781c44067c43175fc) as you rightly pointed out in Slack. Digging into the commits now to see what needs to be done.

**Comment by cjohnhanson** [comment]
@pnadolny13 are you doing this via `meltano-cloud` or via `meltano cloud`?

**Comment by cjohnhanson** [comment]
@pnadolny13 -- I've just merged the change to `cloud` to re-add that `meltano-cloud` entrypoint here. You should be able to run `meltano-cloud` as normal with this branch now.

**Review by tayloramurphy — APPROVED** [review]

**Comment by pnadolny13** [comment]
@cjohnhanson it works for me now! From a little UAT everything worked as expected, the only minor thing I noticed was that the help text for the subcommands is empty for all except `list` and when I explored the other existing commands it looks like they all have help text for subcommands.

Screen Shot 2023-09-06 at 9 41 58 AM

**Comment by cjohnhanson** [comment]
@pnadolny13 good call out, thanks! Just added docstrings for the other subcommands.

**Review by pnadolny13 — APPROVED** [review]

**Pull request merged**
