### PR TITLE
ci: Scan Docker images

### LINKED ISSUE #6062: Enable image security scanning in CI
We can use (multiple) actions from the marketplace for this:
- https://github.com/marketplace/actions/setup-jfrog-cli
- https://github.com/marketplace/actions/container-image-scan
- https://github.com/marketplace/actions/anchore-container-scan

We will want to run these whenever new images are created, as well as whenever dependencies are updated. We'll also want to run this regularly (e.g. daily) as new security vulnerabilities to be discovered and reported despite us not changing anything.

### PR DESCRIPTION
**Pull request by WillDaSilva**
Since we weren't previously doing any container scanning it comes as no surprise that several hundred issues have been flagged by the container scan for each of our 4 containers (one for each supported Python version). We will want to address those in a separate issue.

Closes #6062

### CODE REVIEW

**Comment by WillDaSilva** [comment]
I've enabled [Scanitizer](https://github.com/apps/scanitizer) for the Meltano repository. It's a tool developed by GitHub to make it easy to update the `Azure/container-scan` allow-list.

**Review by tayloramurphy — APPROVED** [review]
Approving docs since it's a small change!

**Comment by edgarrmondragon** [comment]
@WillDaSilva is it safe to trigger the workflow in dry run mode to test it?

**Review by afolson — APPROVED** [review]

**Comment by WillDaSilva** [comment]
> is it safe to trigger the workflow in dry run mode to test it?

@edgarrmondragon It should be safe since it uses the same dry-run logic as previously (which is a bit misleading imo since even in dry-run mode it still uploads one of the images to Docker Hub). At least it's safe if we consider the previous implementation of dry-run safe.

Unfortunately GitHub does not allow you to manually run a workflow using workflow dispatch from a PR, so I'll update it to run on PRs for the sake of testing it. I'll also update it to not push an image to Docker Hub in any scenario. Once we can verify that it's working as intended in this PR, I'll reset the configuration to run on workflow dispatch instead of PRs.

**Comment by WillDaSilva** [comment]
Using https://github.com/meltano/meltano/runs/7367915153?check_suite_focus=true as an example, we can see how the container scan fails. Whether it passes or fails, it provides a link to the results. It'll fail if any of the results have a severity greater than the cutoff we provide, which is currently `4.0`, i.e. medium.

Here's a link directly to the scan results: https://github.com/meltano/meltano/security/code-scanning?query=ref:refs/pull/6410/merge

I think actually addressing the many issues found falls outside of the scope for this PR.

This PR also makes a few changes to how the Docker publish workflow works beyond adding security scanning:
- The `dry-run` workflow input now totally prevents the upload of images, rather than allowing the SHA tagged image to be uploaded.
- Only 1 image is built per Python version, rather than 2 or 3.
- Image tags are now unique. Previously some tags were being set/pushed multiple times.

**Review by aaronsteers — CHANGES_REQUESTED** [review]
@WillDaSilva - Thanks for creating this PR. Only because I'm not confident of the implications here, I'll ask to put a hold request to give time for review and discussion.

**Comment by aaronsteers** [comment]
@WillDaSilva - My reading of sample outputs in your prior comment was that currently the scanning fails with critical findings - and that this would block publish of images to Docker Hub. Is that expected or am I misreading perhaps?

Thanks!

**Comment by aaronsteers** [comment]
@WillDaSilva - As a path to resolve some/most of the critical findings, what do you think of incorporating 

- #3203?

**Comment by WillDaSilva** [comment]
@aaronsteers @edgarrmondragon I've committed [be9a74c](https://github.com/meltano/meltano/pull/6410/commits/be9a74ca1e8bdeeea92e10864bd6e6b48201341d) to make this PR not fail the workflow if vulnerabilities (regardless of their severity) are detected. We can merge this in now, and take care of those issues (i.e. by [improving the base image](https://github.com/meltano/meltano/issues/3203) + additional fixes) later.

**Review by aaronsteers — APPROVED** [review]
Looks great! Merge when ready.

**Review by edgarrmondragon — APPROVED** [review]

**Pull request merged**
