### PR TITLE
docs: Migrate Meltano docs to Docusaurus

### PR DESCRIPTION
**Pull request by tayloramurphy**

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Should we restore `docs/example-library` at least for CI to run as usual?

**Comment by WillDaSilva** [comment]
> Should we restore docs/example-library at least for CI to run as usual?

@edgarrmondragon I was thinking we could just move those out of `docs/`, and into `integration/` since they were never really incorporated into the docs.

**Comment by pnadolny13** [comment]
@tayloramurphy I didnt see anything to comment on in the changelog :thumbsup: . I did notice that the left side nav bar is showing some sections that are currently hidden in the existing docs e.g. Cloud->Sandbox.

**Comment by tayloramurphy** [comment]
@pnadolny13 good call out on that. I'll check with Brightscout.

**Comment by edgarrmondragon** [comment]
I don't know if it's important but search seems to be broken

**Pull request merged**
