### PR TITLE
fix: Redact sensitive values in `config list` output

### LINKED ISSUE #6858: Meltano `config list` and `config set` should print settings with `kind:secret` as `(redacted)`
As reported in slack and I have confirmed locally.

Currently `meltano config set` will print the setting value in clear text after setting it, and similarly, `config list` will print the secret value in clear text as well.

Proposed changes:

1. `meltano config set` would print `(redacted)` in place of the setting value when confirming that the value has been stored.
2. `meltano config list` would print `(redacted)` in place of the current value when printing the list of all settings.

cc @tayloramurphy

### PR DESCRIPTION
**Pull request by ReubenFrankel**
Fix to redact values for sensitive settings (of `kind` `password` or `oauth`) in `config list`. Also minor refactor to display the redacted value in yellow across `config` commands.

`config list`

image

`config set`

image

`config set --interactive`

image

---

Closes #6858

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@ReubenFrankel passwords are already appropriately redacted in interactive mode from what I can see, right? So this should mainly just touch the `config list` command, correct?

**Comment by ReubenFrankel** [comment]
@tayloramurphy Yes. I made a change to display `(redacted)` in yellow across `config list`, `config set` and `config set --interactive`, but we can revert this if not necessary.

**Comment by ReubenFrankel** [comment]
Should this change also redact values from `config` (no sub-command) output?

image

**Comment by tayloramurphy** [comment]
I don't mind the yellow. It brings attention to it since it is doing something different. I'll approve from the Product side, but still needs engineering review.

**Review by tayloramurphy — APPROVED** [review]

**Review by edgarrmondragon — COMMENTED** [review]
LGTM! The missing coverage is only on the patch (i.e. % of the changed code) and it all falls in the interactive code.

**Review by edgarrmondragon — APPROVED** [review]

**Comment by ReubenFrankel** [comment]
> Should this change also redact values from `config` (no sub-command) output?
> 
> image

@edgarrmondragon Should we address this before merging?

**Comment by edgarrmondragon** [comment]
@ReubenFrankel I think the output of `meltano config <plugin name>` is intended for debugging what config the tap or target will be fed, or even for exporting or being used by other tools. So, keeping the raw value there makes sense to me. I'd be curious what @tayloramurphy thinks.

**Comment by tayloramurphy** [comment]
@edgarrmondragon I think the problem with it is that once you run it then the sensitive value is in your terminal output history. I would be ok with some psuedo-interactive action where it displays but once you exit out it removes it all. 

We do have `meltano invoke --dump=config <plugin>` for getting the actual values, which I think is the appropriate method for getting the actual values a connector sees.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I think the problem with it is that once you run it then the sensitive value is in your terminal output history. I would be ok with some psuedo-interactive action where it displays but once you exit out it removes it all.
> 
> We do have `meltano invoke --dump=config <plugin>` for getting the actual values, which I think is the appropriate method for getting the actual values a connector sees.

@tayloramurphy Ok, so thoughts on leaving the behavior of `meltano config <plugin>` as is vs redacting any sensitive values there? If the former, we could deprecate in favor of `meltano invoke --dump=config <plugin>`.

**Comment by tayloramurphy** [comment]
@edgarrmondragon apologies - I misunderstood which subcommand we were talking about. 

Let's keep the scope of this PR small and open a separate issue about secret values in both `meltano config <plugin>` and `meltano invoke --dump=config <plugin>`. I wouldn't be opposed to have an update on this PR to the docs though explaining where sensitive values are redacted!

**Comment by ReubenFrankel** [comment]
@tayloramurphy I can do a docs update. 🙂

**Review by edgarrmondragon — APPROVED** [review]
Thanks @ReubenFrankel!

**Pull request merged**
