### PR TITLE
chore: Enable pre-commit hooks in CI

### LINKED ISSUE #6307: Add lint workflow for GitHub CI

### PR DESCRIPTION
**Pull request by WillDaSilva**
In addition to changing the argument for pyupgrade, this PR also functions to test pre-commit CI integration.

Closes #6307

### CODE REVIEW

**Comment by WillDaSilva** [comment]
I have disabled `pre-commit.ci` for https://github.com/meltano/meltano. I will re-enable it later when I believe the issues it is currently experiencing have been resolved.

**Review by pandemicsyn — APPROVED** [review]
lgtm, for any docs/product folks reviewing and wondering why SVG's where modified. Its because this also includes a bulk new line/trailing space update. @WillDaSilva which is probably worth a mention, in the commit message.

**Review by tayloramurphy — APPROVED** [review]

**Review by edgarrmondragon — APPROVED** [review]

**Comment by WillDaSilva** [comment]
I've disabled PR auto-fixing by default. It can be triggered manually by commenting `pre-commit.ci autofix`.

The pre-commit checks will fail for this PR because the auto-fixes applied to many files with linter issues, and I do not intend to fix all of those linter issues at this time.

**Comment by edgarrmondragon** [comment]
@WillDaSilva is there a way to turn off pre-commit on PRs while this one is in the works. It's auto-fixing: https://github.com/meltano/meltano/pull/6308/commits/e4d4705ea949db5b62d37f3b18235ef9d1920194

**Comment by WillDaSilva** [comment]
@edgarrmondragon Sorry about that. I'll disable it again. It seems to be ready to go now, except it's applying flake8 to the entire repository instead of only the files that have been changed.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Sorry about that. I'll disable it again. It seems to be ready to go now, except it's applying flake8 to the entire repository instead of only the files that have been changed.
> 
> EDIT: It has been disabled for the Meltano repository.

@WillDaSilva cool, thanks. I've reverted the commit.

**Comment by WillDaSilva** [comment]
I just accidentally merged `pre-commit-ci` into `origin/main` while trying to set `origin/HEAD` to `origin/main`. The changes should be harmless, but they were not squashed, and the commit lacks a semantic title. This could be undone, but it's probably safer to just leave it as is rather than try to rewrite the history of the `main` branch.

**Pull request merged**
