### PR TITLE
change: Include Snowplow project & environment contexts with telemetry opt out events

### PR DESCRIPTION
**Pull request by WillDaSilva**
Per the discussion in the data office hours.

### CODE REVIEW

**Comment by WillDaSilva** [comment]
Follow-up discussion: https://github.com/meltano/internal-general/discussions/415

**Review by pandemicsyn — APPROVED** [review]
lgmt! when you go to merge might be worth updating the commit title to reflect that we rolled with both contexts.

**Comment by WillDaSilva** [comment]
> [...] might be worth updating the commit title to reflect that we rolled with both contexts.

@pandemicsyn Done.

**Review by edgarrmondragon — APPROVED** [review]
lgtm!

**Pull request merged**
