### PR TITLE
docs: August Changelog

### PR DESCRIPTION
**Pull request by tayloramurphy**

### CODE REVIEW

**Comment by tayloramurphy** [comment]
FYI @sbalnojan this is the long running PR we can add to for the next changelog.

**Comment by tayloramurphy** [comment]
@sbalnojan I need to add a couple of links once the docs are updated, but this is the changelog for the month!

**Review by edgarrmondragon — APPROVED** [review]

**Comment by sbalnojan** [comment]
One note @tayloramurphy, have you thought about adding a list of external contributors to the change log? It sounds like a nice thing since the releases on GH usually also highlight them.

**Comment by tayloramurphy** [comment]
@sbalnojan not opposed - could just take a little while. Let me see what the effort is.

**Comment by tayloramurphy** [comment]
Ok so where this breaks down is on the Hub and MeltanoLabs side. There's lots of updates there that we're not tracking in release and compiling the contribution activity would be pretty cumbersome. I'd rather just not do it right now as the Changelog isn't necessarily where we'd want to highlight folks anyways.


This PR Is blocked on a few others getting merged:

* #8064 
* one from Leo on the email notifications

**Pull request merged**
