### PR TITLE
test: Test with Python 3.11.5

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
3.11.5 is present in the versions manifest, but it's not yet available for some other reason: https://github.com/actions/python-versions/blob/main/versions-manifest.json

**Review by WillDaSilva — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
well, tests are now passing even with 3.11.4 🤣 

https://github.com/meltano/meltano/actions/runs/6029820408/job/16360233240?pr=8075#step:12:41

**Comment by edgarrmondragon** [comment]
> well, tests are now passing even with 3.11.4 🤣
> 
> [meltano/meltano/actions/runs/6029820408/job/16360233240?pr=8075#step:12:41](https://github.com/meltano/meltano/actions/runs/6029820408/job/16360233240?pr=8075#step:12:41)

It could mean that merging the v3 branch fixed the issues, but it's still weird

**Comment by edgarrmondragon** [comment]
> It could mean that merging the v3 branch fixed the issues, but it's still weird

That does seem to be the case

```console
$ ~/.local/pipx/venvs/meltano@py3114/bin/python -V
Python 3.11.4
$ ~/.local/pipx/venvs/meltano@py3114/bin/meltano --version
meltano, version 3.0.0rc0
$ ~/.local/pipx/venvs/meltano@py3114/bin/meltano add extractor tap-mongodb --variant meltanolabs
Added extractor 'tap-mongodb' to your Meltano project
Variant:        meltanolabs
Repository:     https://github.com/MeltanoLabs/tap-mongodb
Documentation:  https://hub.meltano.com/extractors/tap-mongodb--meltanolabs

Installing extractor 'tap-mongodb'...
Installed extractor 'tap-mongodb'
```

**Comment by edgarrmondragon** [comment]
Ok, the suggestion here https://github.com/actions/setup-python/issues/722#issuecomment-1695730212 seemed to work

**Pull request merged**
