### PR TITLE
fix: Handle case where setting metadata is `None`

### PR DESCRIPTION
**Pull request by WillDaSilva**
Before:
```
$ meltano config meltano set state_backend.uri file:///${MELTANO_ROOT_DIR}/.meltano/state
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

'NoneType' object has no attribute 'is_redacted'
```

After:
```
$ meltano config meltano set state_backend.uri file:///${MELTANO_ROOT_DIR}/.meltano/state
Meltano setting 'state_backend.uri' was set in `meltano.yml`: 'file:////.meltano/state'
```

Instead of setting the non-existent setting, would we rather it error cleanly?

Closes #6937

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@WillDaSilva is the actual problem here that when you do a config for a setting that doesn't exist it gives this error? Looks like this is coming up because EDK things can use the config block however they want technically, right?

**Comment by WillDaSilva** [comment]
> is the actual problem here that when you do a config for a setting that doesn't exist it gives this error?

@tayloramurphy Yes. Whether or not we want to permit setting these settings is unknown to me, but we definitely shouldn't be erroring in this way.

I asked in the PR description:

> Instead of setting the non-existent setting, would we rather it error cleanly?

If we do want it to error cleanly, I can update this PR to do so.

**Comment by tayloramurphy** [comment]
> If we do want it to error cleanly, I can update this PR to do so.

@WillDaSilva I'd say have it execute but give a warning that "this setting is not known to Meltano".

**Comment by WillDaSilva** [comment]
> I'd say have it execute but give a warning that "this setting is not known to Meltano".

There's a nice parallel between that approach and what we do when a setting that does not exist is retrieved, which is emit a warning and return `None`.

**Review by edgarrmondragon — APPROVED** [review]

**Pull request merged**
