### PR TITLE
Let Meltano settings be stored under environments

### LINKED ISSUE #6015: `meltano config meltano set` doesn't work as expected
```
~/Development/meltano-projects/superset-test ❯❯❯ meltano config meltano set discovery_url http://localhost:4000/discovery.yml
2022-06-04T01:36:33.566497Z [info     ] Environment 'dev' is active
Meltano setting 'discovery_url' was set in `meltano_environment`: 'http://localhost:4000/discovery.yml'
Current value is still: 'https://discovery.meltano.com/discovery.yml' (from the default)
```

I'd expect this to store `discovery_url: http://localhost:4000` in `meltano.yml`, but it's nowhere to be found.

### PR DESCRIPTION
**Pull request by DouweM**
Closes https://github.com/meltano/meltano/issues/6015

I think `meltano config meltano set` has been broken since we added `default_environment` 😬 

`ConfigDervice.update_environment_config` was updating the dict in memory, but not actually updating `meltano.yml`, and `ProjectSettingsService.environment_config` was hard-coded to return `{}` and not actually trying to read Meltano's own config from the environment section in `meltano.yml`.

Now `meltano config meltano set discovery_url http://localhost:4000/discovery.yml` works as expected again:

```sh
$ meltano config meltano set discovery_url http://localhost:4000/discovery.yml
2022-06-05T23:38:42.794392Z [info     ] Environment 'dev' is active
Meltano setting 'discovery_url' was set in the active environment in `meltano.yml`: 'http://localhost:4000/discovery.yml'

$ cat meltano.yml
version: 1
default_environment: dev
environments:
- name: dev
  config:
    discovery_url: http://localhost:4000/discovery.yml
- name: staging
- name: prod

$ meltano config meltano list | grep discovery_url
2022-06-05T23:39:46.560584Z [info     ] Environment 'dev' is active
discovery_url [env: MELTANO_DISCOVERY_URL] (default: 'https://discovery.meltano.com/discovery.yml') current value: 'http://localhost:4000/discovery.yml' (from the active environment in `meltano.yml`)
```

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]
This looks good, though linter is not happy and we may need a test. I'll try to address those tomorrow if we want, or in a follow-on PR.

**Comment by kgpayne** [comment]
I think this fixes more of the config weirdness that was blocking #3153 🙌 Thanks @DouweM!

**Comment by DouweM** [comment]
@edgarrmondragon If you can get this over the finish line with CI that'd be much appreciated!

**Comment by aaronsteers** [comment]
@edgarrmondragon - I see you've approved and tests are green (minus lint, which is okay).

Should we proceed to merge or did you want to add additional tests?

**Comment by edgarrmondragon** [comment]
@aaronsteers I've just merged `main` into the PR branch and fixed flake8 complaints. I'll merge if tests are 🟢, or feel free to do it too

**Comment by aaronsteers** [comment]
@DouweM, @tayloramurphy, @kgpayne, @edgarrmondragon  - I think this needs to be reverted so that `meltano` settings are disallowed in environments. Will update this with a link to the action item to hard-fail if Meltano settings are attempted at the environment level.

**Pull request merged**
