### PR TITLE
docs: Remove E(t)LT from tutorial

### PR DESCRIPTION
**Pull request by tayloramurphy**

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]

**Comment by tayloramurphy** [comment]
FYI @sbalnojan @aaronsteers

**Comment by pnadolny13** [comment]
@tayloramurphy I still see a few of these little "t" references in the tutorial like in https://docs.meltano.com/getting-started/part1.

> Throughout this tutorial, we’ll walk you through the creation of a end-to-end modern E(t)LT stack. In this part, we’re going to start with the data extraction process.

Was this PR intending to remove all or just some? If it was all I can make a new PR to remove the few that I see still.

**Comment by tayloramurphy** [comment]
@pnadolny13 I meant to get rid of them all - guess I missed a few!

**Comment by pnadolny13** [comment]
@tayloramurphy no worries, I'll put up a PR with the ones I found 👍 .

**Pull request merged**
