### PR TITLE
chore: add sdist_public with release marker

### PR DESCRIPTION
**Pull request by aaronsteers**
Makes release marker code more portable

### CODE REVIEW

**Comment by aaronsteers** [comment]
@WillDaSilva, @edgarrmondragon, and @pandemicsyn - Can I get your eyes on this?

With this in place, the portable publish mechanism is:

```
make sdist_public
poetry publish --build
```

**Review by WillDaSilva — APPROVED** [review]
These changes themselves look good to me, but I don't this this release-specific step should be in the Makefile at all. I would prefer it only exist in a GitHub action yaml file as one of the steps, since in general (i.e. when the publish workflow is working) it should never be done manually.

**Review by edgarrmondragon — APPROVED** [review]

**Comment by aaronsteers** [comment]
> These changes themselves look good to me, but I don't this this release-specific step should be in the Makefile at all. I would prefer it only exist in a GitHub action yaml file as one of the steps, since in general (i.e. when the publish workflow is working) it should never be done manually.

@WillDaSilva - Definitely I agree that we shouldn't have a manual release process at all, but in the case that CI is broken (today), I prefer to have a fallback method we trust.

**Comment by aaronsteers** [comment]
@WillDaSilva and @edgarrmondragon - Thanks for reviewing.

I'll go ahead and merge and I'll use this for today.

As a manual check between `make sdist_public` and `poetry publish --build`, I think I will run `poetry build` and then check the artifacts by unzipping and confirming the presence of the UI files and the release marker file.

Does this sounds sensible to you?

Note to self:

- This content probably should get back into the handbook in case we have to repeat this.

**Comment by WillDaSilva** [comment]
> Does this sounds sensible to you?

@aaronsteers Yup.

**Pull request merged**
