### PR TITLE
docs: Fix YAML indent on getting started page and fix link to page source in GitHub

### PR DESCRIPTION
**Pull request by jx2lee**
Minor but i fixed document

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]
`docs/_layouts/getting_started.html` and `docs/_layouts/doc.html` seem a bit redundant and the former is only used by `docs/src/_getting-started/index.md`, but that may be worth looking at in a different PR

**Comment by edgarrmondragon** [comment]
Thanks @jx2lee!

**Review by WillDaSilva — APPROVED** [review]
Thank you @jx2lee!

**Comment by jx2lee** [comment]
@edgarrmondragon 
errors found during the tutorial, so I created it with the same PR.
Next time, I'll create them separately. 🥹 Thanks.

@WillDaSilva Thanks, too. 🙏🏼

**Comment by edgarrmondragon** [comment]
@all-contributors please add @jx2lee for doc

**Pull request merged**
