### PR TITLE
fix(deps): Require Flask-Login>=0.6.2 and Werkzeug>=0.2.2

### LINKED ISSUE #6473: [Bug]: Require Flask-Login>=0.6.2 and Werkzeug>=0.2.2
### Meltano Version

2.3.0

### Python Version

NA

### Bug scope

Other

### Operating System

Any

### Description

Latest `Flask-Login` (released 2022-07-25) is compatible with Werkzeug `0.2.2` so we should update our dependencies to use those.

Related:

- #6469 

### Code

```python
NA
```

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Closes #6473

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
Tests are failing seeming due an incompatibility between flask-security and sqlalchemy.

<details><summary>Traceback</summary>

```
app = <Flask 'meltano.api.app'>, api = <FlaskClient <Flask 'meltano.api.app'>>

    def test_plugins_add(self, app, api):
        with app.test_request_context():
>           res = api.post(
                url_for("plugins.add"),
                json={"plugin_type": "extractors", "name": "tap-gitlab"},
            )

/home/runner/work/meltano/meltano/tests/meltano/api/test_security.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/werkzeug/test.py:1140: in post
    return self.open(*args, **kw)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/testing.py:217: in open
    return super().open(
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/werkzeug/test.py:1089: in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/werkzeug/test.py:956: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/werkzeug/test.py:1237: in run_wsgi_app
    app_rv = app(environ, start_response)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:2095: in __call__
    return self.wsgi_app(environ, start_response)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py:78: in __call__
    return app(environ, start_response)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:2080: in wsgi_app
    response = self.handle_exception(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_restful/__init__.py:271: in error_router
    return original_handler(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_restful/__init__.py:271: in error_router
    return original_handler(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:2077: in wsgi_app
    response = self.full_dispatch_request()
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:1525: in full_dispatch_request
    rv = self.handle_user_exception(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_restful/__init__.py:271: in error_router
    return original_handler(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_restful/__init__.py:271: in error_router
    return original_handler(e)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:1521: in full_dispatch_request
    rv = self.preprocess_request()
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask/app.py:1861: in preprocess_request
    rv = self.ensure_sync(before_func)()
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_principal.py:477: in _on_before_request
    identity = loader()
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/flask_security/core.py:261: in _identity_loader
    identity = Identity(current_user.id)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py:481: in __get__
    return self.impl.get(state, dict_)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py:941: in get
    value = self._fire_loader_callables(state, key, passive)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py:972: in _fire_loader_callables
    return state._load_expired(state, passive)
/home/runner/.cache/pypoetry/virtualenvs/meltano-X8Cmc0BF-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/state.py:712: in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

mapper = <Mapper at 0x7f59f02745b0; User>
state = <sqlalchemy.orm.state.InstanceState object at 0x7f59ea88a6a0>
attribute_names = {'active', 'confirmed_at', 'email', 'id', 'identities', 'last_activity_at', ...}
passive = symbol('PASSIVE_OFF')

    def load_scalar_attributes(mapper, state, attribute_names, passive):
        """initiate a column-based attribute refresh operation."""
    
        # assert mapper is _state_mapper(state)
        session = state.session
        if not session:
>           raise orm_exc.DetachedInstanceError(
                "Instance %s is not bound to a Session; "
                "attribute refresh operation cannot proceed" % (state_str(state))
            )
E           sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x7f59e[848](https://github.com/meltano/meltano/runs/7504914651?check_suite_focus=true#step:9:849)2a30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
```

</details>

**Comment by pandemicsyn** [comment]
TIL: https://github.com/meltano/flask-security we use a flask-security.

**Comment by edgarrmondragon** [comment]
> TIL: https://github.com/meltano/flask-security we use a flask-security fork.

@pandemicsyn That's a fork of https://github.com/mattupstate/flask-security which seems abandoned. I wonder if we should just use https://github.com/Flask-Middleware/flask-security/ if it's compatible.

**Comment by pandemicsyn** [comment]
> > TIL: https://github.com/meltano/flask-security we use a flask-security fork.
> 
> @pandemicsyn That's a fork of https://github.com/mattupstate/flask-security which seems abandoned. I wonder if we should just use https://github.com/Flask-Middleware/flask-security/ if it's compatible.

Yea I wonder if in the past we had to pick up maintenance of the abandoned fork. I spun out a separate issue to follow up at some point: https://github.com/meltano/meltano/issues/6490

**Review by pandemicsyn — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
> Yea I wonder if in the past we had to pick up maintenance of the abandoned fork

@pandemicsyn Looking at the commit history in our fork, it seems like we only forked just so we could have a PyPI release with something that was sitting in `master` of the original 😅

**Comment by WillDaSilva** [comment]
@edgarrmondragon Is this PR still relevant?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Is this PR still relevant?

@WillDaSilva Nope :). Closing...

**Pull request closed without merging**
