### PR TITLE
DRAFT: docs: Add docsearch

### PR DESCRIPTION
**Pull request by afolson**

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@afolson this looks awesome! Should the deploy preview be returning results yet? Is this still in draft or is it ready to go?

**Comment by afolson** [comment]
@tayloramurphy Still a draft because it doesn't show the right info (or any info!) due to some config thing I can't figure out. I have a friend who worked at Algolia looking into it later this week because I don't think it's anything I'm doing. Alex looked and couldn't figure it out either.

**Comment by pandemicsyn** [comment]
@afolson just a heads up, I flipped the PR to draft status, hope thats cool 🙇

**Comment by afolson** [comment]
@pandemicsyn My b, thought I'd enabled that already 😬

**Pull request closed without merging**
