### PR TITLE
build: Use `sass` instead of the deprecated `node-sass` library

### LINKED ISSUE #6483: Support Node v16
Currently building the Meltano UI with Node 16 results in a crash while building libsass. [That library is deprecated](https://sass-lang.com/blog/libsass-is-deprecated), so we should switch to using Dart-sass instead.

CC @alexmarple

### PR DESCRIPTION
**Pull request by WillDaSilva**
https://sass-lang.com/blog/libsass-is-deprecated

Closes #6483

### CODE REVIEW

**Comment by WillDaSilva** [comment]
The following vulnerabilities have been detected:

```
src/webapp/yarn.lock » ejs@2.7.4 – Template injection in ejs (critical severity)
  ↪ https://github.com/advisories/GHSA-phwq-j96m-2c2q
src/webapp/yarn.lock » axios@0.19.2 – Server-Side Request Forgery in Axios (high severity)
  ↪ https://github.com/advisories/GHSA-4w2v-q235-vp99
src/webapp/yarn.lock » axios@0.19.2 – Incorrect Comparison in axios (high severity)
  ↪ https://github.com/advisories/GHSA-cph5-m8f7-6c5x
src/webapp/yarn.lock » node-forge@0.10.0 – Improper Verification of Cryptographic Signature in node-forge (high severity)
  ↪ https://github.com/advisories/GHSA-cfm4-qjh2-4765
src/webapp/yarn.lock » node-forge@0.10.0 – Improper Verification of Cryptographic Signature in node-forge (high severity)
  ↪ https://github.com/advisories/GHSA-x4jg-mjrx-434g
src/webapp/yarn.lock » node-forge@0.10.0 – Open Redirect in node-forge (moderate severity)
  ↪ https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
src/webapp/yarn.lock » node-forge@0.10.0 – Improper Verification of Cryptographic Signature in `node-forge` (moderate severity)
  ↪ https://github.com/advisories/GHSA-2r2c-g63r-vccr
src/webapp/yarn.lock » node-forge@0.10.0 – URL parsing in node-forge could lead to undesired behavior. (low severity)
  ↪ https://github.com/advisories/GHSA-gf8q-jrpm-jvxq
src/webapp/yarn.lock » node-forge@0.10.0 – Prototype Pollution in node-forge debug API. (low severity)
  ↪ https://github.com/advisories/GHSA-5rrq-pxf6-6jx5
src/webapp/yarn.lock » simple-git@1.132.0 – Command injection in simple-git (high severity)
  ↪ https://github.com/advisories/GHSA-3f95-r44v-8mrg
src/webapp/yarn.lock » simple-git@1.132.0 – Command injection in simple-git (high severity)
  ↪ https://github.com/advisories/GHSA-28xr-mwxg-3qc8
src/webapp/yarn.lock » node-notifier@5.4.5 – OS Command Injection in node-notifier (moderate severity)
  ↪ https://github.com/advisories/GHSA-5fw9-fq32-wv5p
src/webapp/yarn.lock » node-ipc@9.2.1 – node-ipc behavior change (low severity)
  ↪ https://github.com/advisories/GHSA-3mpp-xfvh-qh37
```

They probably all previously existed. We ought to address them, but that can be done in a separate PR. This PR is sufficient for us to use Node v16, which would previously run into build failures when building `libsass`.

**Review by edgarrmondragon — APPROVED** [review]
@WillDaSilva The UI assets seem to be building OK with `node-sass`. Confirmed by manually triggering the build workflow, downloading the [wheel](https://github.com/meltano/meltano/suites/7553069740/artifacts/311769639) and running the UI.

There are a few sass warnings raised when running `make sdist_public`, though:

```
yarn run v1.22.19
$ vue-cli-service build

-  Building for production...
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, 255) or calc($value / 255)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │     $value: $value / 255
   │             ^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 49:13          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 59:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 13:17  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    src/scss/_index.scss [29](https://github.com/meltano/meltano/runs/7550562320?check_suite_focus=true#step:9:30):9                                       @import
    stdin 6:9                                                       root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
    node_modules/bulma/sass/components/_all.sass 6:9    @import
    node_modules/bulma/bulma.sass 7:9                   @import
    src/scss/_index.scss 29:9                           @import
    stdin 6:9                                           root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($block-spacing, 2) or calc($block-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
1 │ $level-item-spacing: ($block-spacing / 2) !default
  │                       ^^^^^^^^^^^^^^^^^^
  ╵
    node_modules/bulma/sass/components/level.sass 1:23  @import
    node_modules/bulma/sass/components/_all.sass 6:9    @import
    node_modules/bulma/bulma.sass 7:9                   @import
    src/scss/_index.scss 29:9                           @import
    stdin 6:9                                           root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($i, 12) or calc($i / 12)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
62 │       width: percentage($i / 12)
   │                         ^^^^^^^
   ╵
    node_modules/bulma/sass/grid/columns.sass 62:25  @import
    node_modules/bulma/sass/grid/_all.sass 3:9       @import
    node_modules/bulma/bulma.sass 8:9                @import
    src/scss/_index.scss 29:9                        @import
    stdin 6:9                                        root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($i, 12) or calc($i / 12)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
62 │       width: percentage($i / 12)
   │                         ^^^^^^^
   ╵
    node_modules/bulma/sass/grid/columns.sass 62:25  @import
    node_modules/bulma/sass/grid/_all.sass 3:9       @import
    node_modules/bulma/bulma.sass 8:9                @import
    src/scss/_index.scss 29:9                        @import
    stdin 6:9                                        root stylesheet
```

Job log: https://github.com/meltano/meltano/runs/7550562320?check_suite_focus=true#step:9:28

**Review by pandemicsyn — APPROVED** [review]
lgmt - we actually had https://github.com/meltano/meltano/issues/3390 (just realized closed though). I've been rolling with `sass` for a while.

Needs final approval from @alexmarple though before merge.

**Review by alexmarple — APPROVED** [review]
It's working for me. Let's ship it!

**Pull request merged**
