### PR TITLE
Update discovery.yml to match Hub

### PR DESCRIPTION
**Pull request by tayloramurphy**
Corresponding PR to https://github.com/meltano/hub/pull/554/

* This updates the dbt adapter-specific definitions to better match what's on the Hub.

I'll need some help with the JSON schema if someone would be willing to jump in. I tried to follow @edgarrmondragon's PR https://github.com/meltano/meltano/pull/5963/files

### CODE REVIEW

**Comment by aaronsteers** [comment]
@tayloramurphy - Can we also bump the version number on `discovery.yml`?

**Comment by tayloramurphy** [comment]
@aaronsteers bumped the version on the discovery.yml.

I'm going to request assistance to get the tests over the line. It's not clear to me why adding `variant` would cause a failure there.

**Comment by tayloramurphy** [comment]
@aaronsteers @edgarrmondragon bumped version again

**Comment by edgarrmondragon** [comment]
@aaronsteers @tayloramurphy this looks like it'll be good to merge

**Comment by tayloramurphy** [comment]
@aaronsteers please merge once you've approved!

**Review by edgarrmondragon — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
@aaronsteers This is a safe-ish change so I'll go ahead and merge

**Pull request merged**
