### PR TITLE
Add hub_url setting and send X-Project-Id header

### LINKED ISSUE #6013: Make Hub URL a setting to make it easier to test local Hub

### PR DESCRIPTION
**Pull request by DouweM**
Added to ease fixing https://github.com/meltano/meltano/issues/6011 and testing https://github.com/meltano/hub/pull/530:

```
MELTANO_HUB_URL=http://localhost:4000 meltano discover            
MELTANO_HUB_URL=http://localhost:4000 meltano add utility superset
```

### CODE REVIEW

**Comment by DouweM** [comment]
The DiscoveryService was already sending the `X-Project-Id` header, and I assumed the lack of it here was merely an oversight rather than a conscious decision. If it was, though, we can revert that part of the change, but I'd also be curious why!

**Comment by edgarrmondragon** [comment]
@DouweM I had started a draft in https://github.com/meltano/meltano/pull/6002. Happy to take your changes there or continue in your branch, whichever you prefer.

**Comment by edgarrmondragon** [comment]
@aaronsteers @DouweM I merged this branch into https://github.com/meltano/meltano/pull/6002, so I'm gonna close this one, unless you have any objections

**Comment by aaronsteers** [comment]
@edgarrmondragon - Makes sense! Thanks!

**Comment by edgarrmondragon** [comment]
Closing in favor of https://github.com/meltano/meltano/pull/6002

**Pull request closed without merging**
